# Generated by Django 5.0.7 on 2024-07-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
