# Generated by Django 5.0.7 on 2024-07-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_topic_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
