# Generated by Django 5.0.7 on 2024-07-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_subject_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('true_false', 'True false'), ('short_answer', 'Short answer')], max_length=20),
        ),
    ]
